name: NLAND_OFF_SCHEDULE

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script with secret
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DURL: ${{ secrets.DURL }}
          SURL: ${{ secrets.SURL }}
          RCID: ${{ secrets.RCID }}
          HEADER: ${{ secrets.HEADER }}
          PARAMETERS: ${{ secrets.PARAMETERS }}
          SEARCH_COMMENT: ${{ secrets.SEARCH_COMMENT }}
          URL_PREFIX: ${{ secrets.URL_PREFIX }}
          WEBHOOK_URL_JSON: ${{ secrets.WEBHOOK_URL_JSON }}
          WEBHOOK_URL_NEW: ${{ secrets.WEBHOOK_URL_NEW }}
          WEBHOOK_URL_PING: ${{ secrets.WEBHOOK_URL_PING }}
        run: |
          python NLAND_OFF.py
